### ISSUE TITLE
Couldn't Authenticate using Popup

### ISSUE THREAD

**Issue by dirathea** [GoogleWebComponents/firebase-element#105]
Hi team,

I've encounter an error `Uncaught TypeError: Cannot read property 'token' of undefined` while invoke `login()` method.
This issue occurred on latest release of `firebase-element`.

Here's my code : 
```html
<firebase-auth id="auth" location="{{location}}" provider="google" user="{{user}}">
    </firebase-auth>
```

**Comment by ebidel** [comment]
Please post code that repos the issue

**Comment by robdodson** [comment]
Hitting the same issue in our todo-list https://github.com/PolymerLabs/todo-list/issues/12

**Comment by robdodson** [comment]
I wonder if we can do a new release of the element and add a release note mentioning this change?

**Comment by ebidel** [comment]
Already done bro!
