### ISSUE TITLE
firebase.google.com support

### ISSUE THREAD

**Issue by bvhme** [GoogleWebComponents/firebase-element#134]
Hey, any word on 3.0.0 support for firebase.js?

**Comment by mm-gmbd** [comment]
Just saw the updates, immediately came to ask the same question. Using firebase-element for a fairly important project and would like to see this updated to the latest to take full advantage of the new platform

**Comment by bahuma20** [comment]
I wanna have it. NOW!!! It's so awesome! :)

**Comment by gdavalos** [comment]
This probably is already been worked on (or even already done) since the new [app-indexeddb-mirror docs](https://elements.polymer-project.org/elements/app-storage?active=app-indexeddb-mirror) mention a `firebase-query` element

**Comment by cdata** [comment]
Hey guys, we haven't broadly publicized it yet, so please keep this on the down low: https://github.com/Firebase/Polymerfire

**Comment by mm-gmbd** [comment]
@cdata, yahoo!!!

**Comment by Hunsin** [comment]
Will it support firebase.storage feature??

**Comment by cdata** [comment]
@Hunsin Yeah, support for this feature is currently being designed. Track https://github.com/firebase/polymerfire/issues/10 for progress.

**Comment by cdata** [comment]
Polymerfire has been released / announced, and is the official successor to this element for using the Firebase 3.0.0+ SDK. I'm going to close this issue.

**Comment by fareesh** [comment]
I was all ready to #usetheplatform and started a polymer project and decided to jump aboard the Firebase train as well, only to spend 2 hours until I found this here issue :(
