### ISSUE TITLE
Difference between GoogleWebComponents/firebase-element and firebase/polymerfire

### ISSUE THREAD

**Issue by leesander1** [GoogleWebComponents/firebase-element#136]
I was curious as to the difference between this element (firebase-element) and the element [polymerfire ](https://github.com/firebase/polymerfire) from the firebase team. A couple of the newer codelabs use polymerfire but the polymerproject website has firebase-element on the elements page.

**Comment by tjsavage** [comment]
[polymerfire](https://github.com/firebase/polymerfire) is now the official Polymer+Firebase element from the Firebase team, compatible with the new Firebase 3.0 release.  This element uses the previous Firebase 2 API.

We're going to keep the firebase-element API docs up for current users, and will be adding pointers to the new Polymerfire docs as well as the docs themselves to the catalog.

**Comment by maria-le** [comment]
@tjsavage: Will `firebase-auth` be updated to be compatible with Firebase 3.x? Or should we migrate to Polymerfire? ([See this issue #137](https://github.com/GoogleWebComponents/firebase-element/issues/137)).
