### ISSUE TITLE
Firebase 3.x update breaks firebase-auth

### ISSUE THREAD

**Issue by maria-le** [GoogleWebComponents/firebase-element#137]
`firebase-auth` no longer works with the new version of Firebase.

[According to this SO answer](http://stackoverflow.com/a/37511235/1640892):
> If you created your Firebase project on the new Firebase Console, it will only work with the 3.x version of the JavaScript SDK. You'll need an updated version of the component, which doesn't seem to be available yet.

[Here is another version of the same issue on SO](http://stackoverflow.com/q/37606064/1640892).

**Comment by craftyc0der** [comment]
I've been beating my head against this all day. Perhaps this is not my fault after all. No matter what I do I get, "Error: The specified authentication provider is not enabled for this Firebase"
