### ISSUE TITLE
[1.0.0] Computed value method not called correctly on firebase-collection data changes

### ISSUE THREAD

**Issue by hawkett** [GoogleWebComponents/firebase-element#23]
In the example below, computeVal(peeps) is called _before_ the firebase event is logged (as part of element initialisation), and not after - so the only computed value is against the empty list, despite there being a result. Repeated execution reliably gives the same results.

The ```dom-repeat``` works as expected, the ```dom-if``` doesn't.

[JSBin demonstrating the problem] (http://jsbin.com/dufosa/11/edit?html,console,output)

Strong suspicion I'm doing something wrong here, but not sure what - I'm not seeing this problem with firebase-document (or with any other computed values I've been using).

I'm not sure how long the example firebase DB will stick around - it was created as part of the [firebase tutorial](https://www.firebase.com/tutorial/#gettingstarted). Here's the console output:

```
"Adding Firebase event handlers."
"checking..."
[]
"fbase-test Ready"
"Firebase Event: \"child_added\""
[object Object] {
  name: "Rick Astley",
  text: "It's never going to let me down."
}
null
"Firebase Event: \"value\""
[object Object] {
  -ImBnI0WLch7L7ndl6Qd: [object Object] {
    name: "Rick Astley",
    text: "It's never going to let me down."
  }
}
"FIREBASE WARNING: Using an unspecified index. Consider adding \".indexOn\": \"name\" at / to your security rules for better performance "
```

**Comment by cdata** [comment]
In order to correctly measure changes to an array in Polymer's data-binding system, you need to make a binding like this:

`{{didWeGetRolled(peeps.*)}}`

After doing this, `didWeGetRolled` will be notified with "splice" change events related to the array. You can measure the size of the array like this: `change.base.length`.

**Comment by cdata** [comment]
For more detail on this subject, please refer to: https://github.com/Polymer/polymer/blob/master/PRIMER.md#array-observation

**Comment by hawkett** [comment]
Cool - thanks for the heads-up.

Can see now that the docs do say: _The element then produces and maintains an Array of ordered child items_, but it still didn't occur to me that the array was being updated in place rather than replaced. Makes a lot of sense though.

A clarifying note on this in the firebase-element docs would be awesome whenever the next updates come along.
