### ISSUE TITLE
having trouble saving to firebase

### ISSUE THREAD

**Issue by marcus7777** [GoogleWebComponents/firebase-element#24]
do I just update the {{data}} ? If so it's not working.

https://www.youtube.com/watch?v=k-S_K80ItNs

what am i missing?

**Comment by curtiscovington** [comment]
I am pretty sure this is related to the issue I was having: https://github.com/GoogleWebComponents/firebase-element/issues/22

**Comment by curtiscovington** [comment]
Temporary work around, try removing readOnly from the data property.

**Comment by cdata** [comment]
Hi, thanks for reporting. I have fixed this in #28 .
