### ISSUE TITLE
`closeObserver` exceptions using firebase-element

### ISSUE THREAD

**Issue by addyosmani** [GoogleWebComponents/firebase-element#3]
When using the `firebase-element`, I'm currently getting closeObserver exceptions. Verified by another user. Commenting out https://github.com/PolymerElements/firebase-element/blob/master/firebase-element.html#L329 allows the element to be used.

![screen shot 2015-05-08 at 16 41 41](https://cloud.githubusercontent.com/assets/110953/7539769/261874ac-f5a1-11e4-81e6-102b770d0e06.png)

This is probably left over from https://github.com/PolymerElements/firebase-element/commit/876121aeed9cc4d1589fe64d8027c085090046fc#diff-5191c63b6d1dae1e7108cdb4d32a52e2L419

cc @cdata

**Comment by cdata** [comment]
Word, checking it out.

**Comment by cdata** [comment]
This issue was made against an experimental iteration of this element. I'm going to close it for now. Let me know if you think it is still relevant!
