### ISSUE TITLE
Dynamically change location attribute

### ISSUE THREAD

**Issue by dominik0711** [GoogleWebComponents/firebase-element#35]
Is it possible to change the **location** attribute of `firebase-collection` dynamically like this:

```
<firebase-collection
      order-by-child="height"
      limit-to-first="3"
      location="{{myDynamicLocation}}"
      data="{{dinosaurs}}"></firebase-collection>
```

**Comment by lukewil** [comment]
+1 - super interested in the answer to this question!

**Comment by curtiscovington** [comment]
What I did was have a computed location property

```javascript
computeLocation: function(user) {
			if (user) {
				return "https://you-app-here.firebaseio.com/users/" + user.uid;
			}

			else null;
		},
```

**Comment by Whyser** [comment]
Can also confirm that it works to dynamically change the location property. It's really convenient! :D

**Comment by albertolobrano** [comment]
Yes it is possible. I use it all the time with no issues at all

**Comment by ypryviazentsau** [comment]
@albertolobrano Could you please advice some code sample, I wasted hours trying to get it working ...
