### ISSUE TITLE
Polymer 1.0 compatibility

### ISSUE THREAD

**Issue by jenyckee** [GoogleWebComponents/firebase-element#38]
When installing with 

    bower install --save polymer/firebase-element

For polymer 1.0 I get dependency conflicts for webcomponentsjs en polymer

    Unable to find a suitable version for webcomponentsjs, please choose one:
        1) webcomponentsjs#^0.6.0 which resolved to 0.6.3 and is required by polymer#0.5.6
        2) webcomponentsjs#^0.7.2 which resolved to 0.7.6 and is required by polymer#1.0.6, polymer#1.0.6
        3) webcomponentsjs#* which resolved to 0.7.6 and is required by core-component-page#0.5.6

    Unable to find a suitable version for polymer, please choose one:
        1) polymer#^0.5 which resolved to 0.5.6 and is required by firebase-element#0.5.6
        2) polymer#~1.0.0 which resolved to 1.0.6 and is required by platinum-push-messaging#1.0.0
        3) polymer#^1.0.0 which resolved to 1.0.6 and is required by iron-a11y-keys-behavior#1.0.5

**Comment by curtiscovington** [comment]
@jenyckee You are using the wrong command. Try this instead:

```
bower install --save GoogleWebComponents/firebase-element#^1.0.0
```

**Comment by jenyckee** [comment]
Thanks! It's not clear from the polymer catalog site nor firebase site how to install.

**Comment by curtiscovington** [comment]
@jenyckee 
From: https://elements.polymer-project.org/browse?package=google-web-components

Star the element you want. Then click the star in the top right. Click the download tab. 

That should tell you how to install the elements you want.

**Comment by jenyckee** [comment]
Yes, I know but it doesn't. It says "bower install --save" with the "GoogleWebComponents/firebase-element#^1.0.0"

**Comment by curtiscovington** [comment]
@jenyckee 
Right? That is what it is supposed to say? Or am I missing something?

**Comment by jenyckee** [comment]
The command "bower install --save" won't install anything. It would be cool if it said the complete command

**Comment by curtiscovington** [comment]
@jenyckee 
You have to star what you want first. In the list, click the star on elements you want.

**Comment by jenyckee** [comment]
Got it!

**Comment by curtiscovington** [comment]
Cool. I think we can close this issue then. =]
