### ISSUE TITLE
<firebase-auth params="{...}"> is not properly used in login() 

### ISSUE THREAD

**Issue by jeffposnick** [GoogleWebComponents/firebase-element#39]
The `<firebase-auth>` `params` (and `options`) attributes are defined as `type: Object`, meaning that they're automatically deserialized into `Object`s when referenced from JavaScript. The [current `login()` code](https://github.com/GoogleWebComponents/firebase-element/blob/5ac68d72d44fb9c446a85cc2d25513ad52b1a594/firebase-auth.html#L203) attempts to do a `JSON.parse(this.params)`, but that shouldn't be done.

Also, there appears to be a timing issue that prevents `this.params` from being properly set in the `login()` method when `auto-login` is used. One workaround is, as with most Polymer timing issues, wrapping [the call to `this.login()`](https://github.com/GoogleWebComponents/firebase-element/blob/5ac68d72d44fb9c446a85cc2d25513ad52b1a594/firebase-auth.html#L172) in a `this.async()`.

**Comment by cdata** [comment]
Thanks for reporting this. I'll take a look.

**Comment by marcus7777** [comment]
![screenshot email scope](https://cloud.githubusercontent.com/assets/6314260/9435583/fd147142-4a40-11e5-89ca-c41a6acffac3.png) 

No email permission request on the Consent Popup when you add email as a scope

**Comment by marcus7777** [comment]
@jeffposnick like https://github.com/HackITtoday/firebase-element/commit/0e8835e3496f2a5723ab635dfff58c10aa298ce9#l172 ??

**Comment by jeffposnick** [comment]
@marcus7777 it would be `this.async(this.login);`, since the parameter to `this.async()` should be a reference to a function.

**Comment by marcus7777** [comment]
My bad I didn't include the actually it in my code, sorry.
By the way you need to include the attribute params in your firebase auth

**Comment by johnwhitton** [comment]
Has this been fixed?
I'm having a problem trying to get the users email, and am unsure whether I am just using the incorrect syntax or if this is an underlying problem with the element.

**The following works fine (not asking for email)**
`<firebase-auth auto-login redirect location="[[firebaseURL]]" provider="[[firebaseProvider]]" on-error="onFirebaseError" on-login="onFirebaseLogin" on-ref-changed="enableLogging"></firebase-auth>`

**However this gives an error (asking for email)**
`<firebase-auth auto-login redirect location="[[firebaseURL]]" provider="[[firebaseProvider]]" on-error="onFirebaseError" on-login="onFirebaseLogin" on-ref-changed="enableLogging" params='{scope: "email"}'></firebase-auth>`

Error received at firebase.js.137
*Uncaught Error: Firebase.authWithOAuthRedirect failed: third argument must be a valid object.*

**Comment by mm-gmbd** [comment]
+1, for development, having this is important. I'd like to auto-login with the master token, but passing the token in the `params` attribute is generating the following error:

```
<firebase-auth
  ...
  params: '{token: "MASTER_TOKEN}'
>
</firebase-auth>
```

> Uncaught SyntaxError: Unexpected token t

Wrapping token in double quotes still throws in just a slightly different error:

```
<firebase-auth
  ...
  params: '{"token": "MASTER_TOKEN}'
>
</firebase-auth>
```

> Uncaught SyntaxError: Unexpected token o

**Comment by ebidel** [comment]
Passing JSON to an attribute needs to be valid JSON. So double quoted keys.

@johnwhitton 
`params='{scope: "email"}'` needs to be `params='{"scope": "email"}'`

@mm-gmbd Attributes are configured using "=" not ":".

`params: '{"token": "MASTER_TOKEN}'` needs to be `params='{"token": "MASTER_TOKEN"}'`

See https://www.polymer-project.org/1.0/docs/devguide/properties.html#configuring-object-and-array-properties

**Comment by johnwhitton** [comment]
@ebidel Thanks that works, sorry for the inconvenience.

**Comment by ebidel** [comment]
NP :)

**Comment by ebidel** [comment]
BTW, I closed this given the typos in the user examples above and the new release we pushed yesterday. If, after checking out the latest release, anyone is still seeing issues, please let use know.
