### ISSUE TITLE
How to apply non-string values to start-at?

### ISSUE THREAD

**Issue by Mygod** [GoogleWebComponents/firebase-element#40]
`start-at="1"` sets `startAt` to `"1"`. What should I do to set it to `1`?

**Comment by cdata** [comment]
Hello. You can use the `orderValueType` to do this.

Please refer to it here: https://github.com/GoogleWebComponents/firebase-element/blob/master/firebase-collection.html#L182-L199

**Comment by Mygod** [comment]
But I also want to set `endAt=""` so that I can pick out all the positive numbers... How do I do that?
