### ISSUE TITLE
Demo Error: Uncaught TypeError: this.$.firebaseLogin.login is not a function

### ISSUE THREAD

**Issue by maria-le** [GoogleWebComponents/firebase-element#46]
When implementing [the demo](https://github.com/GoogleWebComponents/firebase-element/blob/master/demo/index.html), as written, when using the `anonymous` login option, I get the following errors:

`Uncaught TypeError: Cannot read property 'login' of undefined`
`Uncaught TypeError: this.$.firebaseLogin.login is not a function`

Similar errors occur for `password` option.

**Comment by devAtPolydeals** [comment]
You need to provide more info to solve this issue. Can you put your code on jsedit or something?

**Comment by cdata** [comment]
Hi, thanks for reporting. I will take a look shortly.

**Comment by maria-le** [comment]
Never mind. It was my fault. Close this please.
