### ISSUE TITLE
Problem with hosting

### ISSUE THREAD

**Issue by BorntraegerMarc** [GoogleWebComponents/firebase-element#65]
Hi there

I've build a sample polymer application with the starter kit (V 1.1.0) and pushed it to firebase (https://blazing-heat-376.firebaseapp.com/). Now I wanted to use the firebase element and copied a simple example. Here's my code:
`

    <template is="dom-bind">
      <firebase-collection location="https://blazing-heat-376.firebaseio.com/"
                           data="{{dinosaurs}}"></firebase-collection>

      <template is="dom-repeat" items="[[dinosaurs]]" as="dinosaur">
        <h4>[[dinosaur.__firebaseKey__]]</h4>
        <span>Height: </span><span>[[dinosaur.name]]</span><span>m</span>
      </template>
    </template>
`

Here's my import in the element.html:
`<link rel="import" href="../bower_components/firebase-element/firebase-collection.html">`

When I serve the project with 'gulp serve' everything works fine. But when I try to host the app I get the following error: Uncaught SyntaxError: Unexpected token ILLEGAL

When I remove the import, the site is being displayed fine, but I can't make the backend call. I think there is a problem vulcanizing the element...

**Comment by marcus7777** [comment]
try ```<link rel="import" href="../firebase-element/firebase-collection.html">``` If it is your in element
```<link rel="import" href="bower_components/firebase-element/firebase-collection.html">``` if in index

**Comment by BorntraegerMarc** [comment]
Hello @marcus7777
I have like a separate elements.html, that handels the imports. If I try to paste in your code I get the following error:
`errno: -4058
code: ENOENT
path: D:\Workspaces\polymer-starter-kit-1.1.0\dist\elements\bower_components\firebase-element\firebase-collection.html
fileName: D:\Workspaces\polymer-starter-kit-1.1.0\dist\index.html`

So I don't think, that it is a import problem... Do you have anymore suggestions?

**Comment by BorntraegerMarc** [comment]
Is it possible, that the element has problems being vulcanized?

**Comment by addyosmani** [comment]
I've been using vulcanized versions of the firebase-element with PSK for the last few weeks and didn't run into issues. That said, perhaps we should try vulcanizing a much smaller sample that uses the firebase elements and see if we can repro this outside of PSK?

**Comment by BorntraegerMarc** [comment]
@addyosmani Alright, thanks for the reply. Do you maybe have a sample project or code, where you use firebase with polymer? Maybe I'm using the library wrong... By the way: I'm using PSK 1.1.0 with firebase-elements 1.0.6...

**Comment by BorntraegerMarc** [comment]
@addyosmani Hi there! I tried to vulcanize a smaller example and I'm getting the same error... Do you have a special build/vulcanizing/deployment process?

**Comment by addyosmani** [comment]
@BorntraegerMarc It looks like using PSK 1.1.0 (which uses polybuild/polyclean as part of the pipeline) may well result in some other build issues. One related to Firebase that we're tracking is https://github.com/PolymerLabs/polyclean/issues/4. I can't confirm this is the same cause of the issue you're running into that fails the rest of the build, but it may be related.

**Comment by BorntraegerMarc** [comment]
@addyosmani Yes, that fixed it for me! Thank you very much :) Hope you can fix the bug soon...
