### ISSUE TITLE
Element catalog has no link to the demo

### ISSUE THREAD

**Issue by zoechi** [GoogleWebComponents/firebase-element#68]
https://elements.polymer-project.org/elements/firebase-element?active=firebase-collection

**Comment by zoechi** [comment]
Just realized that this example can probably not be made public because of the required Firebase database. Just close it if it is not planned.

**Comment by steren** [comment]
+1 for the missing demo on the Element catalog. The demo is very useful to understand how login works.

We can find it in the element's sources, so it should be possible to host it and link to it in the catalog.
