### ISSUE TITLE
Firebase-element : Vulcanize issue 

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [GoogleWebComponents/firebase-element#72]
The build of a project using Firebase-element, index.html displays the javascript code minimized
<img width="960" alt="issue" src="https://cloud.githubusercontent.com/assets/4426520/10217646/7b3102ee-6831-11e5-9e1a-eccefb6d6a4c.png">

**Comment by addyosmani** [comment]
Could you provide a repro of the code/commands you're running to reproduce this issue? There's a slight change it's related to https://github.com/PolymerLabs/polyclean/issues/4, but probably not.

**Comment by Geoffrey-Pliez** [comment]
https://github.com/Geoffrey-Pliez/firebase-element-issue.

This simple code create the issue

**Comment by devmikko** [comment]
Just by putting `<link rel="import" href="../bower_components/firebase-element/firebase-collection.html">` on elements.html will cause this issue.

SS
https://slack-files.com/T03PF4L4C-F0BRR2KSR-b2a1d0ebc7
https://slack-files.com/T03PF4L4C-F0BRVSM16-e8de6e987e

**Comment by gpoulet** [comment]
same thing here ! :(

**Comment by jesusabarca** [comment]
I'm having the same issue.

**Comment by Geoffrey-Pliez** [comment]
The guilty file is "firebase/firebase.js".
I have commented  this file and Vulcanize work.

**Comment by cyberj** [comment]
Same here with fresh PSK + firebase element

**Comment by Geoffrey-Pliez** [comment]
I have no more the problem since a PSK on master branch + firebase-element 1.0.8
