### ISSUE TITLE
user-created event does not include uid of newly registered user

### ISSUE THREAD

**Issue by Protoss78** [GoogleWebComponents/firebase-element#74]
The firebase API returns the UID of the newly generated user, but the firebase-auth element does not include the information in the event details. This makes it quite cumbersome to implement a custom registration process.

**Comment by Protoss78** [comment]
This modification worked for me:
```javascript
createUser: function(email, password) {
        this.ref.createUser({email: email, password: password}, function(error, detail) {
          if (!error) {
            this.fire('user-created', detail);
          } else {
            this.fire('error', error);
          }
        }.bind(this));
      }
```

**Comment by albertolobrano** [comment]
this is what i do: 

1) call firebase-auth.createUser.
2) on the event : user-created -> I call firebase-auth.login
3) the login returns the user object with the id and other stuff

**Comment by Protoss78** [comment]
I've found the login workaround already in a couple of firebase forums. I think there was even a modification request that requested this as a feature. Therefore it was later included in its API. From my perspective the web component should not block already existing API logic. I can provide the needed change in a pull request.

**Comment by oathcomrade** [comment]
+1

**Comment by MeTaNoV** [comment]
+1

**Comment by MeTaNoV** [comment]
what I miss more generally is also a verification email for a 2 step registration process like found in nearly all websites...

**Comment by ebidel** [comment]
Merged in https://github.com/GoogleWebComponents/firebase-element/pull/59/files
