### ISSUE TITLE
Upgrade firebase dep to 2.3.1

### ISSUE THREAD

**Issue by albertolobrano** [GoogleWebComponents/firebase-element#90]
Some great features have being added to firebase like Multi-path updates. We should upgrade to the last version.

**Comment by addyosmani** [comment]
Let's verify that nothing breaks as a result of updating to 2.3.1.

**Comment by albertolobrano** [comment]
I will give it  a try right now and let you know

**Comment by albertolobrano** [comment]
On my system: tests and application is running fine.   I will create a pr for this

**Comment by bvhme** [comment]
Yeah, the Deep path querying is something that I'd love for my product right now!

**Comment by addyosmani** [comment]
Now in master!
