### ISSUE TITLE
How to check successful login

### ISSUE THREAD

**Issue by BartKoppelmans** [GoogleWebComponents/firebase-element#94]
Hello,

Is there a possibility to check if the login was successful? There is the `error` event, but is there something like a `succes` event?

Bart

**Comment by albertolobrano** [comment]
there is a login event that get fired and provides you the user object. 

        this.fire('login', {user: user});


so you can have something like: 

 listeners: {
      login: '_handleLogin',
      error: '_handleError'
    },
