### ISSUE TITLE
Authenticate to Firebase with oauth-token

### ISSUE THREAD

**Issue by IchordeDionysos** [GoogleWebComponents/firebase-element#96]
It would be cool if you implement the Firebase authWithOAuthToken() method.

I really need to have it.

Thanks in advance.

[Firebase.authWithOAuthToken](https://www.firebase.com/docs/web/api/firebase/authwithoauthtoken.html)

**Comment by johnlim** [comment]
Isn' t this supported in pull request #101?

**Comment by ebidel** [comment]
Yea :)

**Comment by IchordeDionysos** [comment]
Cool guys :+1:  Love it
